version: '3.7'
services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: saude_bem_estar
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./script:/docker-entrypoint-initdb.d